### ISSUE TITLE
disk.frame%>%filter(variable_values%in%includes) might not work if includes are not instantiated as variable

### ISSUE THREAD

**Issue by KnutJaegersberg** [xiaodaigh/disk.frame#191]
the filter example stored in  `compare<-` does not work for me as expected, gives me back all of the data. whereas `compare2<-` filter does work as expected:

```r
library(disk.frame)
library(dplyr)
library(nycflights13)

setup_disk.frame()

options(future.globals.maxSize = Inf)

flights<-flights

compare1<-flights%>%filter(tailnum%in%paste0(unique(flights$tailnum)[1:60], ""))

flights_df<-as.disk.frame(nycflights13::flights)

compare<-flights_df%>%filter(tailnum%in%paste0(unique(flights$tailnum)[1:60]), "")%>%collect()

include<-paste0(unique(flights$tailnum)[1:60], "")
compare2<-flights_df%>%filter(tailnum%in%include)%>%collect()
```

**Comment by xiaodaigh** [comment]
There is a bug with `disk.frame` that silently fails on invalid syntax.

The problem is with this line


compare<-flights_df%>%filter(tailnum%in%paste0(unique(flights$tailnum)[1:60]**)**, "")%>%collect()

Do you see the misplaced **(**. After fixing that both works on the `development branch`

```r
include <- paste0(unique(flights$tailnum)[1:60], "")

compare2<-flights_df %>%
  filter( tailnum %in% include) %>%
  collect()



compare <- flights_df %>%
  filter(tailnum %in% paste0(unique(flights$tailnum)[1:60], "")) %>% 
  collect()

nrow(compare2)  == nrow(compare) # return TRUE
```
So the real issue is that disk.frame is silently failing! See how the statement in question actually fails on normal `dplyr`

``` r
flights %>% 
 filter(tailnum %in% paste0(unique(flights$tailnum)[1:60]), "")
#> Error in flights %>% filter(tailnum %in% paste0(unique(flights$tailnum)[1:60]), : could not find function "%>%"
```

<sup>Created on 2019-10-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by xiaodaigh** [comment]
BTW do you actually want this as your criterion? `c(unique(flights$tailnum)[1:60], ""))`

**Comment by KnutJaegersberg** [comment]
yeah sure^^ just a typo. glad to have helped anyway :)
