### ISSUE TITLE
dplyr mutate verb not working as expected?

### ISSUE THREAD

**Issue by BearMills** [xiaodaigh/disk.frame#274]
Hi, 

Not sure if this is an actual issue/bug with `disk.frame` but I recently just came across the package (and I am relatively new to `R`).

I have been testing the package (developer version) with some data files and I ran into a minor issue using `mutate` 

If I run another `dplyr` verb such as `select` or `filter` the code works as expected. For example: 

    test <- diskframe %>% select("ITEMS") %>% collect

this returns a `data.frame` with the specified column selected (`ITEMS`). 

However, if I run this with `mutate` it does not correctly evaluate the code. For example: 

    test <- diskframe %>% 
    select("ITEMS") %>%
    mutate(ITEMS_2 = ITEMS / 3) %>%
    collect

This returns a `data.frame` with only a single column containing `ITEMS` but does not contain a new variable `ITEMS_2`. Also no errors are thrown in the console. 

It is not until I explicitly state `dplyr::mutate` that the code evaluates correctly and returns the `data.frame` with the new variable. 

Is it intended to work like this? Having read most of the user guides they do not explicitly state the `package::function` but I have seen a few workarounds for other issues where this is explicitly stated.  

PS. Really nice package - I stumbled across this and has been fantastic for working with large data files

**Comment by xiaodaigh** [comment]
Hi @BearMills, I can't replicate your error

```r
library(disk.frame)
setup_disk.frame()


mtcars.df = as.disk.frame(mtcars)

mtcars.df %>% 
  select("mpg") %>% 
  mutate(mpg2=mpg/3) %>% 
  collect
```

The issue that sometimes `dplyr::select` needs to be called instead of `select` is that `select` happens to be a function export by packages other than `dplyr` hence if the packages are not imported in the right order then `select` refers to the other pacakge's `select` not `dplyr::select`.

`mutate` might fall into the same issue. Can you see if `?mutate` or `??mutate` tells you if `mutate` belongs to two different packages?

I will close this for now, if you come across the issue again, please provide a minimal workable example, so I can reconstruct `diskframe`.
