### ISSUE TITLE
group_by having different results between dplyr and data.table syntax

### ISSUE THREAD

**Issue by Waldi73** [xiaodaigh/disk.frame#310]
See https://stackoverflow.com/a/63929173/13513328 for a reprex.
In issue 309 I made a syntax error which I corrected.
In this issue, for `data.table` syntax I don't find the error and don't understand why the `n_distinct` returns `n(weeks) * n(disk.frames)` rows.
Thanks for your great work, and your feedback on this!

**Comment by xiaodaigh** [comment]
There is no syntax error, that is currently how data.table works. data.table syntax development is lagging dplyr syntax development, so we need this to be implemented #239 

Since this is a dup of the above, and I will close this once I have updated the docs and the article.

In fact, I am thinking about moving data.table syntax support to a different package.


I need to support this article to make it more clear.
https://diskframe.com/articles/05-data-table-syntax.html

**Comment by Waldi73** [comment]
Thanks for your feedback
I actually read the article about `data.table` and it made me believe `group by` wouldn't be a problem :
> **All data.table syntax are supported**. However, disk.frame adds the ability to load only those columns required for the analysis using the keep = option. In the above analysis, only the year and month variables are required and hence keep = c("year", "month") was used.

Perhaps clarify what is included in **All**.

New to `disk.frame` and already realizing its potential : great work, thanks!
