### ISSUE TITLE
Error in serialize(data, node$con) : error writing to connection

### ISSUE THREAD

**Issue by jianlianggao** [xiaodaigh/disk.frame#314]
Hi,

I read a huge csv using disk.frame into small chunks. Now I want to use mutate to generate a new column, which contains date information. 
The line I used to load the huge dataset (12GB) is as follows.
`df<-csv_to_disk.frame("CompustatDaily.csv", outdir = "compustat.df", in_chunk_size = 3e6, overwrite = T)`
The df information is:
path: "compustat.df"
nchunks: 48
nrow (at source): 165539283
ncol (at source): 10

When I ran `mutate(df, date = as.Date(as.character(datadate), format="%Y%m%d"))`, I got the following error:
`Error in serialize(data, node$con) : error writing to connection`

Any idea? Many thanks.
J

**Comment by xiaodaigh** [comment]
You seem to be doing everything correctly.

I have noticed this error happens when the multiprocessing which {future} controls has bugs.

I suggest updating {future} and your R version if you have not already done so. 

Are you able to share the data?

If not do this

a) Check if your virus scanner is blocking interprocess communication

b) Try to apply the function to just one chunk, perhaps there is a syntax error or column error? If one chunk works then you can rule out coding error

```
get_chunk(df, 1) %>%
  mutate(date = as.Date(as.character(datadate), format="%Y%m%d"))
```

c) Set the number of workers to 1, so there is no more interprocesssing communication. Does it work now? If it does, then it's the inter process communication. You might need to contact your admin for help

```
setup_disk.frame(workers=1)
mutate(df, date = as.Date(as.character(datadate), format="%Y%m%d"))
```

As an MWE this works for me.

```
a = data.frame(datadate = rep("20201007", 3e6))

library(disk.frame)

setup_disk.frame()

df<-as.disk.frame(a)


df1 = mutate(df, date = as.Date(as.character(datadate), format="%Y%m%d"))

head(df1)
```

**Comment by jianlianggao** [comment]
Many thanks for your reply. Is {future} a package? I will try with 1 worker and see how it goes. The data is 12GB, the compressed one is about 1GB. I can share it with you. Can you please send me your email address in a confidential way if you don't want to leave it here? Search my name in Google. You will find my contact. :-)

**Comment by jianlianggao** [comment]
My issue is gone. I just quit RStudio and restarted it. I don't know what happened. Thank you very much.
