### ISSUE TITLE
rbindlist.diskframe runs out of memory

### ISSUE THREAD

**Issue by herryATcsiro** [xiaodaigh/disk.frame#317]
Hi there,
rbindlist.disk.frame(m2,outdir='df/MSPA.df', by_chunk_id = T, parallel=F, overwrite=T)
with m2 being a list of 100 diskframes fails with
"Error: cannot allocate vector of size 7.9 Gb
Timing stopped at: 223.2 1504 2559"

I have tried reducing workers down to 1 to no avail.
Any suggestions?

running on linux R 3.6.3 using Rstudio

**Comment by xiaodaigh** [comment]
I suspect your chunk sizes might bee too large.

So you have 100 disk.frames! Each of which might blow out the memory.

I believe the algorithm is like take all chunk 1s from each disk.frame and rbind them and then save that as chunk 1, and take all chunk 2s and rbind them etc..

So if each of the rbind is too large then there are issues.

The other thing you can do is to try and double the number of chunks in each disk.frame so that you are using less memory.

Like 

```
m2_new = lapply(m2, function(diskf) {
  nc = nchunks(diskf)
  tf = tempfile()
  diskf2 = rechunk(diskf, nc*2, outdir = tf)
  diskf2
})

rbindlist.disk.frame(m2_new,outdir='df/MSPA.df', by_chunk_id = T, parallel=F, overwrite=T)
```

**Comment by herryATcsiro** [comment]
Thanks,
Does that mean rbindlist.disk.frame will always create only 1 chunk for the combined disk.frames?

**Comment by xiaodaigh** [comment]
No. It creates one chunk for each chunk id.
