### ISSUE TITLE
the interchange between disk.frame and data.frame

### ISSUE THREAD

**Issue by GreenEric** [xiaodaigh/disk.frame#64]
Dear Xiaodai,
Thanks for the great work of releasing R from the constraint of RAM. As a heavy user of data.table, I am wondering how I can seamlessly working with data.table(DT) and disk.frame(DF) together.
I tried few time, and found that. After converting a dataset into DF format, the common DT way is still workable, but when I need to assign it to a new variable, the new variable automatically becomes a DT.

```
DF <- as.disk.frame(
  data.table(X=rep(letters[1:5],2), Y=1:10),
  outdir = "temp",
  overwrite = T
)

class(DF)   #[1] "disk.frame"        "disk.frame.folder"
class(DF[,.N, by = .(X)]) #[1] "data.table" "data.frame"
```
It seems that the disk.frame serves as a storage keeper. It does save lot of space by saving everything in warehouse, and get things out for others to process.
Am I right?
Thanks for the great work again,
Eric

**Comment by xiaodaigh** [comment]
Thanks for your question. It is correct that using `[` will return the result as a data.table. However, this behaviour will likely CHANGE in the next major version!

Currently, disk.frame is a storage mechanism that stores all the data on disk.

The way I see disk.frame as useful is that one can use it to manipulate large data and once they are happy with the final form of the data they can then sample from it or summarise it so that the result is small enough and can be bought into RAM.

If you want to keep the result as a disk.frame, you can only do this with the `delayed` function and use the `collect` to bring the results into R. Unfortunately, data.table syntax for doing this is not yet supported, so you have to use dplyr syntax.

For example, `DF_summ` is a `disk.frame`, not a `data.table`
```r
DF_summ = DF %>% 
  srckeep("X") %>% 
  group_by(X) %>% 
  summarise(N = n())
```
when you use `collect`, it becomes a data.table
```r
DF_DT = collect(DF_summ)
```
In the next major version, I want to make `class(DF[,.N, by = .(X)])` return a `"disk.frame"`.

**Comment by xiaodaigh** [comment]
Also `DF[,.N, by = .(X), keep="X"]` would be faster if `DF` is large and has many columns.
