### ISSUE TITLE
Plan to submit to cran

### ISSUE THREAD

**Issue by dipterix** [xiaodaigh/disk.frame#76]
Hi, is there any plans to make this package on cran?

**Comment by xiaodaigh** [comment]
Yes. But I need major work on `dplyr` compatibility as `verb_` is no longer recommended. And I only work on disk.frame on Sunday mornings so it might take some time.

**Comment by georgevbsantiago** [comment]
Hello, I read your package information on the UseR! 2019 and found it fantastic.
I would like to know the package `tidyr` works with` disk.frame`?
If not, do you want to implement it with `disk.frame`?

I have a case that your package would help a lot. I reported the case to the `vroom` ([link](https://github.com/r-lib/vroom/issues/151)) package repository.

Follow the example I reported:

My example is a peculiar case.

The Federal Revenue Service of Brazil publishes data in a single file (10Gb) with several data.frame agglutinated, in a fwf format.

So we have to read part of the file (with read_lines_chunked ()) and treat the chunk with a function executed with callback [SideEffectChunkCallback] and then write the result to a CSV or DBMS.

We repeat this until we read every file (or files, as there may be more than one).

I'll try to sketch an example:

```
library(readr)
library(tidyr)
library(tibble)
library(magrittr)

# Imagine a 10Gb data.frame in the example below
# Imagine reading this date.frame in pieces of 100,000 rows in each loop of `read_lines_chunked()`

dfs_fwf <- tibble::tibble(lines_fwf = c(
                                        "1aaabbbbccccc",
                                        "2ddddddeeeeeeeffffffff",
                                        "3zzxxkk",
                                        "3zzxxkk",
                                        "1aaabbbbccccc",
                                        "1aaabbbbccccc",
                                        "2ddddddeeeeeeeffffffff",
                                        "1aaabbbbccccc",
                                        "2ddddddeeeeeeeffffffff",
                                        "3zzxxkk",
                                        "2ddddddeeeeeeeffffffff",
                                        "1aaabbbbccccc"
                                        )
                                        )



# Imagine that this would be part of the function executed by `callback[SideEffectChunkCallback]`

dfs_fwf_index <- dfs_fwf %>%
                 tidyr::separate(lines_fwf,
                                 into = c("index", "col_dfs_fwf"),
                                 sep = c(1)
                                 )

df_fwf_1 <- dfs_fwf_index %>%
            dplyr::filter(index == 1) %>%
            tidyr::separate(col_dfs_fwf,
                            into = c("col_A", "col_B", "col_C"),
                            sep = c(3, 7, 12))

df_fwf_2 <- dfs_fwf_index %>%
            dplyr::filter(index == 2) %>%
            tidyr::separate(col_dfs_fwf,
                            into = c("col_D", "col_E", "col_F"),
                            sep = c(6, 13, 21))

df_fwf_3 <- dfs_fwf_index %>%
            dplyr::filter(index == 3) %>%
            tidyr::separate(col_dfs_fwf,
                            into = c("col_Z", "col_X", "col_K"),
                            sep = c(2, 4, 6))

readr::write_csv(df_fwf_1, "csv_df_fwf_1", append = TRUE)
readr::write_csv(df_fwf_2, "csv_df_fwf_2", append = TRUE)
readr::write_csv(df_fwf_3, "csv_df_fwf_3", append = TRUE)
```
Created on 2019-07-08 by the reprex package (v0.3.0)

I was successful in developing the code to handle the data because of the read_lines_chunked () function to read the file in parts + callback [SideEffectChunkCallback] to process and write the result to a CSV or a DBMS.

A function that has the same functionality in the vroom package would be very important.

**Comment by xiaodaigh** [comment]
@georgevbsantiago I have moved Ur isse to #88 as this issue is about submitting to CRAN

**Comment by xiaodaigh** [comment]
just submitted
